# Generated by Django 5.0.3 on 2024-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sncfunchained',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=50)),
                ('heure_depart', models.DateTimeField(verbose_name=50)),
                ('heure_arrivee', models.DateTimeField(max_length=50)),
            ],
        ),
    ]
